services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
     - N8N_RUNNERS_ENABLED=true
     - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
     - SHEET_ID_CHISTES=1vedoe_lG1FxF5YlDdtOw7J8xETcSiMIVmwM8qlFsUjg
     - SHEET_NAME_PROG=Programming
     - SHEET_NAME_MISC=Misc
     - SHEET_NAME_DARK=Dark
    volumes:
      - ./local-files:/files
      - ./database.sqlite:/home/node/.n8n/database.sqlite
      - n8n_data:/home/node/.n8n

  web:
    build: ./task-manager-service/web
    restart: always
    container_name: task-manager-web
    ports:
      - "5001:5000"
    volumes:
      - ./task-manager-service/web:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taskdb
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - db
      - mq

  worker:
    build: ./task-manager-service/worker
    restart: always
    container_name: task-manager-worker
    volumes:
      - ./task-manager-service/worker:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - mq

  notifier:
    build: ./task-manager-service/notifier
    restart: always
    container_name: task-manager-notifier
    volumes:
      - ./task-manager-service/notifier:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
      - WEBHOOK_URL=https://webhook.site/6affa107-8c08-4d45-99c8-b84d076b6784
    depends_on:
      - mq

  error_handler:
    build: ./task-manager-service/error_handler
    restart: always
    container_name: task-manager-error-handler
    volumes:
      - ./task-manager-service/error_handler:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - mq

  db:
    image: postgres:14-alpine
    container_name: task-manager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    ports:
      - "5433:5432" 

  mq:
    image: rabbitmq:3-management-alpine
    container_name: task-manager-mq
    ports:
      - "5672:5672" 
      - "15672:15672"

volumes:
  n8n_data:
  postgres_data: