services:
  web:
    build: ./web
    restart: always
    container_name: task-manager-web
    ports:
      - "5001:5000"
    volumes:
      - ./web:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taskdb
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - db
      - mq

  worker:
    build: ./worker
    restart: always
    container_name: task-manager-worker
    volumes:
      - ./worker:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - mq

  notifier:
    build: ./notifier
    restart: always
    container_name: task-manager-notifier
    volumes:
      - ./notifier:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
      - WEBHOOK_URL=https://webhook.site/6affa107-8c08-4d45-99c8-b84d076b6784
    depends_on:
      - mq

  error_handler:
    build: ./error_handler
    restart: always
    container_name: task-manager-error-handler
    volumes:
      - ./error_handler:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - mq

  db:
    image: postgres:14-alpine
    container_name: task-manager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    ports:
      - "5433:5432" 

  mq:
    image: rabbitmq:3-management-alpine
    container_name: task-manager-mq
    ports:
      - "5672:5672" 
      - "15672:15672"

volumes:
  postgres_data:
