services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
     - N8N_RUNNERS_ENABLED=true
     - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    volumes:
      - ./local-files:/files
      - ./database.sqlite:/home/node/.n8n/database.sqlite
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: